@ContosoPizza_HostAddress = http://localhost:5044

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Mother's Receipe",
    "isGlutenFree": true
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/4
Content-Type: application/json

{
    "name": "Hawaiian",
    "isGlutenFree": true
}

###

DELETE {{ContosoPizza_HostAddress}}/pizza/3
Content-Type: application/json