@ContosoPizza_HostAddress = http://localhost:5044

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Pepperoni Margherita",
    "isGlutenFree": false
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/8
Content-Type: application/json

{
    "name": "Vegetarian Delight",
    "isGlutenFree": true
}

###

DELETE {{ContosoPizza_HostAddress}}/pizza/11
Content-Type: application/json