@ContosoPizza_HostAddress = http://localhost:5044

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###

POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Chicken Sausage",
    "isGlutenFree": false
}

###

PUT {{ContosoPizza_HostAddress}}/pizza/4
Content-Type: application/json

{
    "name": "Spicy Volcano",
    "isGlutenFree": true
}

###

DELETE {{ContosoPizza_HostAddress}}/pizza/5
Content-Type: application/json